# FLOW CONDITIONAL STATEMENTS
# SAMPLE IF STATEMENTS
'''idcard=input("do you have a idcard(yes/no):")
if(idcard.lower()=="yes"):
    print("Enter in to the caratRed ofc")
    print("allow check in")
    print("njoy the work")
print("\nGo to Home and Read the Bible")'''


'''r=int(input("Enter a number:"))
if (r>0):
    print("{}is positive".format(r))
if (r<0):
    print("{}is Negative".format(r))
if (r==0):
    print("{}is zero".format(r))
print("Program completed")'''
